<?php
/*
 * MikoPBX - free phone system for small business
 * Copyright © 2017-2025 Alexey Portnov and Nikolay Beketov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace Modules\ModuleExampleRestAPIv3\Models;

use MikoPBX\Common\Models\ModelsBase;

/**
 * Tasks Model - Phalcon ORM model for m_ModuleExampleRestAPIv3_Tasks table
 *
 * WHY: Demonstrates database table definition using Phalcon annotations
 * Auto-creates table during module installation via PbxExtensionSetup
 *
 * PATTERN: Standard MikoPBX model pattern
 * - Extends ModelsBase for common functionality
 * - Uses Phalcon annotations (@Column, @Primary, @Identity)
 * - Defines table name in initialize()
 * - Includes uniqid field for safe public ID exposure
 *
 * HOW DATABASE TABLES ARE CREATED:
 * 1. PbxExtensionSetup scans Models/ folder during installation
 * 2. Reads Phalcon annotations from model properties
 * 3. Auto-generates CREATE TABLE SQL based on annotations
 * 4. Creates m_ModuleExampleRestAPIv3_Tasks table
 *
 * IMPORTANT FIELDS:
 * - id: Auto-increment primary key (internal use only)
 * - uniqid: Public-facing unique identifier (use in API instead of id)
 * - title: Task title (required)
 * - status: Task status (pending, in_progress, completed)
 * - priority: Task priority (0-10)
 *
 * @package Modules\ModuleExampleRestAPIv3\Models
 */
class Tasks extends ModelsBase
{
    /**
     * Auto-increment primary key
     *
     * WHY: Internal database ID (do not expose in public API)
     * Use $uniqid field for public-facing API responses
     *
     * @Primary
     * @Identity
     * @Column(type="integer", nullable=false)
     */
    public int $id;

    /**
     * Unique identifier for public API
     *
     * WHY: Safe to expose in API (UUID format)
     * Prevents enumeration attacks on sequential IDs
     * Auto-generated by ModelsBase::beforeValidation()
     *
     * @Column(type="string", nullable=false)
     */
    public string $uniqid;

    /**
     * Task title
     *
     * Required field, max 255 characters
     *
     * @Column(type="string", nullable=false)
     */
    public string $title;

    /**
     * Task status
     *
     * Valid values: 'pending', 'in_progress', 'completed'
     * Default: 'pending'
     *
     * @Column(type="string", nullable=true)
     */
    public ?string $status = 'pending';

    /**
     * Task priority level
     *
     * Range: 0-10 (higher = more important)
     * Default: 5 (medium priority)
     *
     * @Column(type="integer", nullable=true)
     */
    public ?int $priority = 5;

    /**
     * Initialize model
     *
     * WHY: Sets database table name for this model
     * Table naming convention: m_{ModuleName}_{TableName}
     *
     * IMPORTANT: Must call parent::initialize() to:
     * - Set up automatic uniqid generation
     * - Enable automatic timestamps (if configured)
     * - Register model relationships
     */
    public function initialize(): void
    {
        $this->setSource('m_ModuleExampleRestAPIv3_Tasks');
        parent::initialize();
    }
}
